services:
  whisperfusion:
    build:
      context: docker
      dockerfile: docker/Dockerfile.gpu
    image: whisperfusion:latest
    volumes:
      - type: bind
        source: ./docker/scratch-space
        target: /root/scratch-space
    environment:
      VERBOSE: ${VERBOSE:-false}
      MODEL: ${MODEL:-Phi-3-mini-4k-instruct}
    ports:
      - "8888:8888"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    entrypoint: ["/root/scratch-space/run-whisperfusion.sh"]

  ws-client-nginx:
    image: nginx:1.14.2
    volumes:
      - ./docker/resources/docker/default:/etc/nginx/conf.d/default.conf:ro
      - ./examples/chatbot/html:/var/www/html:ro
    ports:
      - "8000:80"
    #depends_on:
    #  - whisperfusion
    extra_hosts:
      - "whisperfusion:${HOST_IP}"
